import { ApiForm } from "../_components/api-form";
import { WorkflowPage } from "../_components/workflow-page";

export default function ReportsPage() {
  return (
    <WorkflowPage
      apiRoutes={["POST /api/reports", "GET /api/reports/[id]"]}
      doneItems={[
        "Monthly report stores an immutable snapshot payload.",
        "Report includes readiness, workload, routine, alert, and benchmark confidence context.",
        "Reports avoid diagnosis and unsupported ranking language."
      ]}
      eyebrow="Review workflow"
      primaryItems={[
        "Generate monthly player reports from snapshot inputs.",
        "Add parent weekly and coach roster summaries after player report is stable.",
        "Store generated PDF or web artifact in Azure Blob Storage later.",
        "Keep report text parent-readable and action-focused."
      ]}
      summary="Reports convert tracked data into safe monthly review material for parents, players, and coaches."
      title="Reports"
    >
      <ApiForm
        description="Creates an immutable monthly player report snapshot."
        endpoint="/api/reports"
        fields={[
          { name: "organizationId", label: "Organization ID", required: true },
          { name: "playerId", label: "Player ID", required: true },
          { name: "generatedByUserId", label: "Generated by user ID", placeholder: "optional" }
        ]}
        title="Generate monthly player report"
      />
    </WorkflowPage>
  );
}
